
# let assuming that there is not variable x
'''
The try block lets you test a block of code for errors.

The except block lets you handle the error.

The else block lets you execute code when there is no error.

The finally block lets you execute code, regardless of the result of the try- and except blocks.
'''
# code here :

try:
    print(x) #x is not defind
except:
    print('an execption occoured')
    